import 'package:flutter/material.dart';
import '../models/lead.dart';

class LeadsScreen extends StatefulWidget {
  const LeadsScreen({super.key});

  @override
  State<LeadsScreen> createState() => _LeadsScreenState();
}

class _LeadsScreenState extends State<LeadsScreen> {
  final List<Lead> _leads = [
    Lead(
      businessName: 'Sample Lead Co',
      contactEmail: 'contact@sample.com',
      generatedEmail: 'Email will be generated by AI...',
      portfolioPitch: 'Pitch will be generated by AI...',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Discovered Leads'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: _leads.isEmpty
          ? const Center(child: CircularProgressIndicator())
          : ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: _leads.length,
              itemBuilder: (context, index) {
                final lead = _leads[index];
                return Card(
                  margin: const EdgeInsets.only(bottom: 12),
                  child: Padding(
                    padding: const EdgeInsets.all(14),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(lead.businessName,
                            style: const TextStyle(
                                fontSize: 16, fontWeight: FontWeight.bold)),
                        const SizedBox(height: 4),
                        Text(lead.contactEmail,
                            style: const TextStyle(color: Colors.grey)),
                      ],
                    ),
                  ),
                );
              },
            ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => Navigator.pushNamed(context, '/results'),
        label: const Text('See Results'),
        icon: const Icon(Icons.arrow_forward),
      ),
    );
  }
}