import 'package:flutter/material.dart';
import '../models/lead.dart';

class LeadsScreen extends StatefulWidget {
  const LeadsScreen({super.key});

  @override
  State<LeadsScreen> createState() => _LeadsScreenState();
}

class _LeadsScreenState extends State<LeadsScreen> {
  bool _isLoading = true;
  final List<Lead> _leads = [];
  List<Lead> _filteredLeads = [];
  final _searchController = TextEditingController();

  @override
  void initState() {
    super.initState();
    _loadLeads();
    _searchController.addListener(_filterLeads);
  }

  void _filterLeads() {
    final query = _searchController.text.toLowerCase();
    setState(() {
      _filteredLeads = _leads.where((lead) =>
        lead.businessName.toLowerCase().contains(query) ||
        lead.contactEmail.toLowerCase().contains(query)
      ).toList();
    });
  }

  Future<void> _loadLeads() async {
    await Future.delayed(const Duration(seconds: 2));
    setState(() {
      _leads.addAll([
        Lead(
          businessName: 'Tech Solutions Ltd',
          contactEmail: 'hello@techsolutions.com',
          generatedEmail: 'Email will be generated by AI...',
          portfolioPitch: 'Pitch will be generated by AI...',
        ),
        Lead(
          businessName: 'Creative Agency Co',
          contactEmail: 'contact@creativeagency.com',
          generatedEmail: 'Email will be generated by AI...',
          portfolioPitch: 'Pitch will be generated by AI...',
        ),
        Lead(
          businessName: 'Digital Marketing Hub',
          contactEmail: 'info@dmhub.com',
          generatedEmail: 'Email will be generated by AI...',
          portfolioPitch: 'Pitch will be generated by AI...',
        ),
      ]);
      _filteredLeads = List.from(_leads);
      _isLoading = false;
    });
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Discovered Leads'),
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: _isLoading
          ? const Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 16),
                  Text('Finding leads...'),
                ],
              ),
            )
          : Column(
              children: [
                Padding(
                  padding: const EdgeInsets.all(12),
                  child: TextField(
                    controller: _searchController,
                    decoration: InputDecoration(
                      hintText: 'Search leads...',
                      prefixIcon: const Icon(Icons.search),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      contentPadding: const EdgeInsets.symmetric(vertical: 10),
                    ),
                  ),
                ),
                Expanded(
                  child: _filteredLeads.isEmpty
                      ? const Center(child: Text('No leads found.'))
                      : ListView.builder(
                          padding: const EdgeInsets.symmetric(horizontal: 12),
                          itemCount: _filteredLeads.length,
                          itemBuilder: (context, index) {
                            final lead = _filteredLeads[index];
                            return Card(
                              margin: const EdgeInsets.only(bottom: 12),
                              elevation: 2,
                              child: Padding(
                                padding: const EdgeInsets.all(16),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Row(
                                      children: [
                                        const Icon(Icons.business,
                                            color: Colors.indigo),
                                        const SizedBox(width: 8),
                                        Text(lead.businessName,
                                            style: const TextStyle(
                                                fontSize: 16,
                                                fontWeight: FontWeight.bold)),
                                      ],
                                    ),
                                    const SizedBox(height: 8),
                                    Row(
                                      children: [
                                        const Icon(Icons.email,
                                            size: 14, color: Colors.grey),
                                        const SizedBox(width: 6),
                                        Text(lead.contactEmail,
                                            style: const TextStyle(
                                                color: Colors.grey)),
                                      ],
                                    ),
                                    const SizedBox(height: 10),
                                    Container(
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 10, vertical: 4),
                                      decoration: BoxDecoration(
                                        color: Colors.indigo.shade50,
                                        borderRadius:
                                            BorderRadius.circular(20),
                                      ),
                                      child: const Text('AI Ready',
                                          style: TextStyle(
                                              fontSize: 11,
                                              color: Colors.indigo)),
                                    ),
                                  ],
                                ),
                              ),
                            );
                          },
                        ),
                ),
              ],
            ),
    );
  }
}